### ISSUE TITLE
Integrator forward euler

### ISSUE THREAD

**Issue by lucastepper** [lucastepper/gle_sim#3]
Progress on the integrator looks good. Looking at the function _integrate, it looks mostly correct to me. In the line:
```
        v[i+1] = v[i] + config.dt 
            * ((-config.k_harm*x[i])/config.m + (&k*(&y-x[i])).sum());  
```
Keep in mind that the all the eom are m * dv/dt = F[x(t)].
So the right side term calculating k_i * [y_i(t) - x(t)] should also be divided by m. 
Furthermore, should it not be &y[i] ?
For the update of y_i
```
        y[i+1] = y[i] + config.dt 
            * (-config.k[i]*(y.row(i)-x[i])/gamma[i]);  
```
just add the random force, and it should be correct. 
Then check that p(x) ~= N[0, sqrt(kbt / k)] and p(v) ~= N[0, sqrt(kbt / m)], where N[\mu, \sigma] is a standard normal distribution with mean \mu and std \sigma.

**Comment by MrBTTF** [comment]
@lucastepper 
```
Furthermore, should it not be &y[i] ?
```
Your're right. Thanks a lot!

I pushed the code. 

```
Then check that p(x) ~= N[0, sqrt(kbt / k)] and p(v) ~= N[0, sqrt(kbt / m)], where N[\mu, \sigma] is a standard normal distribution with mean \mu and std \sigma.
```
I was trying to compare plots with distributions that you're defined but I get very small std which makes sense because kB is very small. However, x,y,v have different scale and their distribution are not that normal. Could you have a look?

**Comment by lucastepper** [comment]
It should probably be &y[i]. I wrote some comments on the commit.

**Comment by lucastepper** [comment]
Hi Vlad,

I had a look at your code and added some comments:
https://github.com/lucastepper/gle_sim/commit/8e1ddc7975151eba24cd8246497a7ab96e349f77
Hopefully the distributions match now.

Greetings
Lucas
